### ISSUE TITLE
Simplify Angular Approach with Globals

### ISSUE THREAD

**Issue by joebochill** [pxblue/internationalization#1]
#### Bug or feature request?
Feature Request

#### What is the expected behavior?
Import the language variable without having to extend basecomponent for every component in your application.

#### What is the current behavior?
Each component that wants to use the current language file has to extend BaseComponent.

#### What is your environment?

 Framework
- [x] Angular
- [ ] React
	
#### Anything else to add?
See [this](https://stackblitz.com/edit/angular-shared-globals?file=src/app/component3.ts) for a potential approach using globals.

**Comment by emclaug2** [comment]
I'm closing this issue because the ng i18n example has been rewritten.
